server:
  port: 9328

security:
  jwt:
    public-key: classpath:public.txt


spring:
  jackson:
    serialization:
      INDENT_OUTPUT: true
  datasource:
    url: jdbc:mysql://localhost:3306/movimentacoes?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: root  
  jpa.properties.hibernate.dialect : org.hibernate.dialect.MySQL8Dialect
 


#MessageSource
message:
  source.basename : classpath:messages/messages_pt_BR.properties
  source.use.code.as.default.message : true

 
